__default__:
    account: # specify default account here
    partition: # specify default partition here
    time: 3-00:00:00
    nodes: 1
    ntasks: 1
    mem: 5GB
    output: "logs/{rule}.{wildcards.sample}.out"
    error: "logs/{rule}.{wildcards.sample}.err"