restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
#cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60

# added snakemake settings for automation with HPC
use-conda: True
jobs: 10
keep-going: True
rerun-incomplete: True
