# slurm submission arguments
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --nodes={resources.nodes}
    --ntasks-per-node={resources.ntasks}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
# sets default resources for all jobs submitted; resources defined in rule will override these
default-resources:
  - partition=tb
  - mem_mb=10000
  - nodes=1
  - ntasks=1
  - time="3-00:00:00"
# sets maximum resources allocated to all jobs submitted at the same time
resources:
  - cpus=30
  - mem_mb=75000
# other snakemake specific default arguments
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
conda-frontend: conda