############################ Set Globals ############################
samples: ../config/samples.tsv
## ploidy level for organism of interest
ploidy: 2
## default number of cores for rules without specification below; change as desired
cores: 1

############################ Required Input ############################

## placeholders for required arguments; if not specified here or at command line, pipeline will not run!
## Note: these parameters may be updated manually below prior to running the pipeline (if updated here,
## no need to add on the command line)
reference: False
data: False
mode: None

############################ Overall Pipeline Parameters ############################

## defaults to applying all callers; change to False to prevent any caller from running
use_haplotypecaller: True
use_freebayes: True
use_bcftools: True
## set to False to prevent applying base quality score recalibration
apply_bqsr: True
## set to False to prevent variant annotation using SnpEff
apply_snpeff: False
## set to False to prevent ploidy evaluation analysis
check_ploidy: False

############################ STAR ############################

## default parameters for STAR reference indexing; change as desired
sjdbOverhang: 150
sjdbGTFtag: Parent
genomeSAindexNbases: 12
star_index_cores: 8

## default parameters for STAR alignment; change as desired
outFilterType: BySJout
outFilterMultimapNmax: 10
alignSJoverhangMin: 8
alignSJDBoverhangMin: 1
outFilterMismatchNmax: 999
outFilterMismatchNoverReadLmax: 0.04
alignIntronMin: 20
alignIntronMax: 1000000
alignMatesGapMax: 1000000
quantMode: GeneCounts
star_align_cores: 8

############################ Hisat2 ############################

## default cores for Hisat2 indexing
hisat_index_cores: 8

## default parameters for Hisat2 alignment; change as desired
minintronlen: 20
maxintronlen: 500000
## default cores for Hisat2 alignment
hisat_align_cores: 8

############################ BWA ############################

## default parameteres for bwa index; change as desired
algorithm: bwtsw
## default cores for bwa alignment
bwa_mem_cores: 8

############################ Base Quality Score Recalibration ############################

## set cores for tools allowing user specification
hap_bqsr_cores: 8
mutect_cores: 1

## default parameters for GATK's AddOrReplaceReadGroups tool; change as needed
pl: illumina
pu: LANLbyDefault

## default parameters for GATK's VariantFiltration -- SNPs (Note: these filters are used for BQSR 
## and germline calling w/HaplotypeCaller)
QD_filter_snp: QD < 2.0
FS_filter_snp: FS > 60.0
MQ_filter_snp: MQ < 40.0
SOR_filter_snp: SOR > 4.0
MQRankSum_filter_snp: MQRankSum < -12.5
ReadPosRankSum_filter_snp: ReadPosRankSum < -8.0

## default parameters for GATK's VariantFiltration -- INDELs
QD_filter_indel: QD < 2.0
FS_filter_indel: FS > 60.0
SOR_filter_indel: SOR > 4.0

############################ Freebayes ############################

## default parameters for Freebayes variant calling method; change as desired
chunksize: 100000
min_alternate_count: 2
min_alternate_freq: 0.01
min_coverage: 10
min_map_qual: 20
min_base_qual: 20
## default cores for freebayes
free_cores: 1

## optional parameter for filtering Freebayes calls by QUAL field; default set at 20 (change as desired)
qual_filter_free: 20

############################ Bcftools ############################

## default parameters for Bcftools variant calling method; change as desired
## mpileup options
bcftools_cores: 1
max_depth: 300
min_MQ: 20
min_BQ: 20
## call options
caller: -m  # either -m or -c; -m by default
## filter options
qual_filter_bcf: QUAL > 20  # set to include variants above quality threshold
depth_filter_bcf: DP > 10   # set to include variants above depth threshold

############################ HaplotypeCaller - GATK ############################

## default cores for haplotypecaller
hap_caller_cores: 8
## filtering parameters for haplotypecaller; removes variant below defined threshold
qual_filter_hapcaller: QUAL < 20
## minimum phred-scaled confidence threshold at which variant should be called for RNA-seq data
stand_call_conf: 20

############################ Variant Intersection ############################

## number of files variant must be at least present in to output to final call set for each mode
## Note: When running in DNA mode, there will be 1 vcf file generated from each caller 
## for each sample (i.e., if all callers are activated, 3 total vcf files will be generated). 
## However, if running in RNA mode, there will be 2 vcf files generated from each caller for 
## each sample, one per aligner (i.e., if all callers are activated, 6 total vcf files will 
## be generated). So, if running in DNA mode, it is recommended to set the DNA parameter to at least 
## 2. For RNA input, setting the RNA parameter to at least 4 is recommended.
nfiles_DNA_mode: 2
nfiles_RNA_mode: 4
## when True, only 1 output vcf file will be written (GATK by default); when False, all files are subset and output
#output_combined: True

############################ SnpEff Annotation ############################

## default cores for SnpEff
snpeff_cores: 4
## Use this parameter to specify reference genome with pre-built SnpEff database (ex: to use the pre-built human 
## reference database, enter 'GRCh38.99'); to get a list of databases available for SnpEff download, 
## run 'snpeff databases' in command line if SnpEff is installed or check in the snpEff.config file for the full 
## list available
## If no pre-built database is available for your organism and wish to run SnpEff, a database can be built from 
## the reference files in the reference folder specified at the command line. To build a database, set this parameter 
## to False (NOTE: keep parameter set to False even if database has previously been built for organism of interest)
database: False