# sge submission arguments
cluster:
  mkdir -p logs/{rule} &&
  qsub
    -q {resources.queue}
    -pe smp {threads}
    -l h_vmem={resources.mem_mb}M
    -l h_rt={resources.time}
    -N smk-{rule}-{wildcards}
    -j y
    -o logs/{rule}/{rule}-{wildcards}-$JOB_ID.out
    -cwd
    -S /bin/bash
    -V
    # options to send email to user if job aborts or completes; uncomment if desired
    #-m ae
    #-M <email>

# sets default resources for all jobs submitted; resources defined in rule will override these
default-resources:
  - queue=tb
  - mem_mb=10000
  - time="3-00:00:00"

# sets maximum resources allocated to all jobs submitted at the same time
resources:
  - cpus=30
  - mem_mb=75000

# other snakemake specific default arguments
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
# set to True if removing locking mechanism
nolock: True